name: create-release

on:
  workflow_call:
    outputs:
      upload_url:
        description: "The release upload URL"
        value: ${{ jobs.create_release.outputs.upload_url }}
      release_version:
        description: "The release version"
        value: ${{ jobs.get_version.outputs.release_version }}

jobs:
  create_release:
    name: Create Release
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_version: ${{ steps.get_version.outputs.release_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Get Version
        id: get_version
        run: |
          TAGVERSION=$(git describe --tags --exact-match)
          value=`echo "${TAGVERSION:1}"`
          echo TEST ECHO
          echo "$value"
          echo "name=release_version::$value"
          echo "test again"
          echo "::set-output name=release_version::$value"
