name: create-release

on:
  workflow_call:
    outputs:
      upload_url:
        description: "The release upload URL"
        value: ${{ jobs.create_release.outputs.upload_url }}

jobs:
  create_release:
    name: Create Release
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
