name: publish-python-package

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
    secrets:
      TEST_PYPI_API_TOKEN:
        required: true
      PYPI_API_TOKEN:
        required: true

jobs:
  publish_python_package:
    name: Publish Python Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install build
      - name: Set Version
        run: sed -i "s/VERSION_REPLACE/${GITHUB_REF_NAME:1}/g" setup.cfg
      - name: Build Package
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
