name: test-python

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  test_python:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      # - name: Setup
      #   run: |
      #     python -m pip install --upgrade pip
      #     python -m pip install --upgrade setuptools wheel
      #     python setup.py install
      - name: Test
        run: |
          cd tests
          python -m unittest discover
          cd ..
