name: test-python

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string

jobs:
  test_python:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Test
        run: |
          cp -a src/. tests/
          cd tests
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover
