name: upload-butler

on:
  workflow_call:
    inputs:
      itch_user:
        required: true
        type: string
      project_name:
        required: true
        type: string
      release_asset_url_ubuntu_latest:
        required: true
        type: string
      release_asset_url_macos_latest:
        required: true
        type: string
      release_asset_url_windows_latest:
        required: true
        type: string
    secrets:
      BUTLER_API_KEY:
        required: true

jobs:
  upload_butler:
    name: Upload Butler
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - channel: "ubuntu-latest"
            asset-url: ${{ inputs.release_asset_url_ubuntu_latest }}
          - channel: "macos-latest"
            asset-url: ${{ inputs.release_asset_url_macos_latest }}
          - channel: "windows-latest"
            asset-url: ${{ inputs.release_asset_url_windows_latest }}
    steps:
      - name: Download Asset
        run: curl -L -o asset.zip ${{ matrix.asset-url }}
      - name: Unzip Asset
        run: |
          mkdir dist
          unzip asset.zip -d dist
      - name: Post Unzip
        if: startsWith(matrix.channel, 'windows') != true
        run: chmod +x dist/${{ inputs.project_name }}
      - name: Download Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Upload With Butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push dist ${{ inputs.itch_user }}/${{ inputs.project_name }}:${{ matrix.channel }} --userversion "${GITHUB_REF_NAME:1}"
